// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdC7er9SRwlfV6Wq7Uad_4IVhnBq7ao5k',
    appId: '1:1004387670266:web:80eb7f46f9e7a491df9143',
    messagingSenderId: '1004387670266',
    projectId: 'cocoa-project-daccd',
    authDomain: 'cocoa-project-daccd.firebaseapp.com',
    storageBucket: 'cocoa-project-daccd.appspot.com',
    measurementId: 'G-7V30WFSDYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqlgm7wPS_5j8CUciZLcsT_aPL0jnY-IU',
    appId: '1:1004387670266:android:c381e99001e1777bdf9143',
    messagingSenderId: '1004387670266',
    projectId: 'cocoa-project-daccd',
    storageBucket: 'cocoa-project-daccd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Kjr4KdVXucsh0Z_PKsIxQ_aYn7h-0B4',
    appId: '1:1004387670266:ios:a2f38b5d7790a91adf9143',
    messagingSenderId: '1004387670266',
    projectId: 'cocoa-project-daccd',
    storageBucket: 'cocoa-project-daccd.appspot.com',
    iosClientId: '1004387670266-o3qhmimlem16bt9annr61o5qf9ojn4ph.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocoaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Kjr4KdVXucsh0Z_PKsIxQ_aYn7h-0B4',
    appId: '1:1004387670266:ios:360fb25b6ee3a85edf9143',
    messagingSenderId: '1004387670266',
    projectId: 'cocoa-project-daccd',
    storageBucket: 'cocoa-project-daccd.appspot.com',
    iosClientId: '1004387670266-pg2vfrvn4l9ccnm8ef9nb2lm5he9u08f.apps.googleusercontent.com',
    iosBundleId: 'com.example.cocoaProject.RunnerTests',
  );
}
